version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: shady_db
    environment:
      POSTGRES_USER: shady
      POSTGRES_PASSWORD: shady
      POSTGRES_DB: shadyrest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    container_name: shady_backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shadyrest
      SPRING_DATASOURCE_USERNAME: shady
      SPRING_DATASOURCE_PASSWORD: shady
    depends_on:
      - db
    ports:
      - "8080:8080"
  ui:
    build: ./shady-rest-ui
    container_name: shady_ui
    depends_on:
      - backend
    ports:
      - "4200:80"
volumes:
  pgdata:
